# Generated by Django 4.0.4 on 2022-05-08 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_display',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
